// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD7501_NailBookingSystem.Data;

#nullable disable

namespace SD7501_NailBookingSystem.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD7501_NailBookingSystem.Models.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 8m,
                            Type = "French Tip"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 8m,
                            Type = "Nail Art"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 8m,
                            Type = "Sticker and Gems"
                        });
                });

            modelBuilder.Entity("SD7501_NailBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingOrder = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            BookingOrder = 2,
                            Name = "Jasmine"
                        },
                        new
                        {
                            Id = 3,
                            BookingOrder = 3,
                            Name = "Kelly"
                        });
                });

            modelBuilder.Entity("SD7501_NailBookingSystem.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            Cost = 40m,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac.",
                            ImageUrl = "",
                            Type = "Manicure Gel"
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 1,
                            Cost = 40m,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac.",
                            ImageUrl = "",
                            Type = "Pedicure Gel"
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 2,
                            Cost = 55m,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac.",
                            ImageUrl = "",
                            Type = "SNS"
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 2,
                            Cost = 60m,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac.",
                            ImageUrl = "",
                            Type = "Acrylic"
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 3,
                            Cost = 50m,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac.",
                            ImageUrl = "",
                            Type = "BIAB"
                        });
                });

            modelBuilder.Entity("SD7501_NailBookingSystem.Models.Service", b =>
                {
                    b.HasOne("SD7501_NailBookingSystem.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
